### ISSUE TITLE
HashSet.addAll does not work correctly

### ISSUE THREAD

**Issue by CodingPfeffer** [j4ts/j4ts#17] opened 2017-06-18 18:57 UTC
```
public boolean addAll(Collection<? extends E> c) {
	checkNotNull(c);

	boolean changed = false;
	for (E e : c) {
	  changed |= add(e);
	}
	return changed;
}
```
is wrongly translated to
```
AbstractCollection.prototype.addAll$java_util_Collection = function (c) {
	javaemul.internal.InternalPreconditions.checkNotNull(c);
	var changed = false;
	for (var index123 = c.iterator(); index123.hasNext();) {
		var e = index123.next();
		{
			changed = changed || this.add(e);
		}
	}
	return changed;
};
```
`changed |= add(e);`
seems not to be equal to
`changed = changed || this.add(e);`
My guess is, that an early return happens if "changed" is true. And "this.add(e)" is not evaluated for further iterations. The java version uses a bitwise OR, but the javascript version uses a logical OR (which may return early).

I also guess that the j4ts candy is created by using the jsweet transpiler. This would mean that jsweet is broken.

A workaround for now is to iterate over the set yourself and use the "add" method.

**Comment by schaumb** [comment] 2018-07-03 02:13
I close this ticket, because the transpiler is changed, so this bug is not reproducible

**Closed** 2018-07-08 07:34 UTC
